### ISSUE TITLE
why only 256 x 256 resulotion 

### ISSUE THREAD

**Issue by mostafablender** [nuanarchy/ComfyUI-NuA-BIRD#3]
Hi  can you explain to me why its only work on 256x256 resolution and not higher  ? i just want to learn about it

**Comment by nuanarchy** [comment]
This is just an implementation of the node for ComfyUI. It's better to ask this question to the model's authors.
https://github.com/hamadichihaoui/BIRD

However, as far as I understand, this is a limitation of the pre-trained model. The method described in the article does not have such limitations
